/**
 * Bakes every bitmap the server-side radio-schedule share card needs into one
 * base64 TypeScript module.
 *
 * Same two constraints as the setlist card's `build-share-card-{assets,embeds}`
 * pair, which is why this exists at all:
 *
 *   1. Satori supports neither CSS `filter` nor stylesheets, so the treatment
 *      `.wl-radio-schedule-share-export__bg-img` applies in the browser
 *      (`grayscale(35%) brightness(0.8)` at `opacity: 0.9` over the frame
 *      colour) has to be baked into the file. The wash gradient on top is a
 *      plain `linear-gradient`, which Satori does support, so that stays in
 *      the card.
 *   2. Nothing may be read from disk at runtime. Supabase Edge bundles only the
 *      reachable module graph, and Netlify's esbuild bundler is no friendlier to
 *      sibling files — anything the renderer needs arrives as code.
 *
 * Unlike the setlist backgrounds this crops to 9∶16 (the story frame) rather
 * than 4:5, so it cannot reuse `share-card-assets/*-card.jpg`.
 *
 * Run: deno run -A scripts/build-schedule-share-card-embeds.ts
 */
import { Image } from "https://deno.land/x/imagescript@1.3.0/mod.ts"

const PUBLIC_DIR = new URL("../public/", import.meta.url)
const OUT_DIR = new URL(
  "../supabase/functions/_shared/schedule-share-card/generated/",
  import.meta.url,
)

/** Matches WL_HOME_V2_SHARE_BACKGROUNDS, minus the file extensions. */
const BACKGROUNDS = [
  { stem: "newbg", file: "newbg.png" },
  { stem: "newbg2", file: "newbg2.jpeg" },
  { stem: "newbg3", file: "newbg3.jpeg" },
  { stem: "newbg4", file: "newbg4.jpeg" },
] as const

/**
 * 9∶16 at a little over the 480px design width, so the JPEG still has detail
 * left when the card is rendered out at 1080. Larger is wasted: the background
 * is behind a heavy wash gradient.
 */
const BG_W = 630
const BG_H = 1120
const BG_QUALITY = 52

/** `.wl-radio-schedule-share-export__frame` background, which 0.9 opacity sits over. */
const FRAME_RGB = [49, 58, 52] as const
const GRAYSCALE = 0.35
const BRIGHTNESS = 0.8
const OPACITY = 0.9

/** The mark sits in a 48px box at 72%; 160px leaves headroom at a 2.25x render. */
const BRAND_MARK_PX = 160

/** Scale to fill, then centre-crop — the equivalent of `object-fit: cover`. */
function cover(img: Image, w: number, h: number): Image {
  const scale = Math.max(w / img.width, h / img.height)
  const rw = Math.ceil(img.width * scale)
  const rh = Math.ceil(img.height * scale)
  const resized = img.resize(rw, rh)
  return resized.crop(Math.floor((rw - w) / 2), Math.floor((rh - h) / 2), w, h)
}

/** grayscale() then brightness(), per the CSS filter order, then composite. */
function applyCardTreatment(img: Image): Image {
  const bmp = img.bitmap
  for (let i = 0; i < bmp.length; i += 4) {
    const r = bmp[i]!, g = bmp[i + 1]!, b = bmp[i + 2]!
    const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    let nr = r + (lum - r) * GRAYSCALE
    let ng = g + (lum - g) * GRAYSCALE
    let nb = b + (lum - b) * GRAYSCALE
    nr *= BRIGHTNESS
    ng *= BRIGHTNESS
    nb *= BRIGHTNESS
    bmp[i] = Math.round(FRAME_RGB[0] * (1 - OPACITY) + nr * OPACITY)
    bmp[i + 1] = Math.round(FRAME_RGB[1] * (1 - OPACITY) + ng * OPACITY)
    bmp[i + 2] = Math.round(FRAME_RGB[2] * (1 - OPACITY) + nb * OPACITY)
    bmp[i + 3] = 255
  }
  return img
}

function toBase64(bytes: Uint8Array): string {
  let binary = ""
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return btoa(binary)
}

const kb = (n: number) => `${(n / 1024).toFixed(0)}KB`

await Deno.mkdir(OUT_DIR, { recursive: true })

let src =
  `// GENERATED by scripts/build-schedule-share-card-embeds.ts — do not edit.\n` +
  `// Radio schedule share card bitmaps, base64. Embedded rather than read from\n` +
  `// disk because neither Supabase Edge nor Netlify's bundler uploads sibling\n` +
  `// files; only the reachable module graph ships.\n\n`

// ---------- backgrounds ----------
src += `/** Story-cropped (9∶16) and pre-treated, keyed by background stem. */\n`
src += `export const SCHEDULE_BACKGROUND_DATA_URI: Record<string, string> = {\n`
let bgBytes = 0
for (const bg of BACKGROUNDS) {
  const raw = await Deno.readFile(new URL(bg.file, PUBLIC_DIR))
  const treated = applyCardTreatment(cover(await Image.decode(raw), BG_W, BG_H))
  const jpg = await treated.encodeJPEG(BG_QUALITY)
  bgBytes += jpg.length
  src += `  "${bg.stem}":\n    "data:image/jpeg;base64,${toBase64(jpg)}",\n`
  console.log(`${bg.stem.padEnd(8)} ${kb(raw.length).padStart(8)} -> ${kb(jpg.length).padStart(7)}`)
}
src += `}\n\n`

// ---------- brand mark ----------
const markRaw = await Deno.readFile(new URL("WTED3.png", PUBLIC_DIR))
const markImg = await Image.decode(markRaw)
const markScale = BRAND_MARK_PX / Math.max(markImg.width, markImg.height)
const markPng = await markImg
  .resize(Math.round(markImg.width * markScale), Math.round(markImg.height * markScale))
  .encode(9)
src += `/** WTED3.png, the schedule card's brand mark (the setlist card uses WL-mark). */\n`
src += `export const SCHEDULE_BRAND_MARK_DATA_URI =\n  "data:image/png;base64,${toBase64(markPng)}"\n\n`
console.log(`WTED3    ${kb(markRaw.length).padStart(8)} -> ${kb(markPng.length).padStart(7)}`)

await Deno.writeFile(new URL("assets.ts", OUT_DIR), new TextEncoder().encode(src))
console.log(
  `\nassets.ts  ${kb(bgBytes)} of backgrounds -> ${kb(src.length)} source`,
)
console.log("Wrote supabase/functions/_shared/schedule-share-card/generated/assets.ts")
