/**
 * Embeds the share-card fonts and background images as base64 TypeScript modules.
 *
 * Supabase Edge Functions bundle only the reachable module graph — arbitrary
 * files sitting next to the source are NOT uploaded, and `Deno.readFile` on
 * them fails at runtime with "path not found". Anything the renderer needs has
 * to arrive as code, so it is generated into `_shared/setlist-share-card/generated/`.
 *
 * Both variants are embedded: `-card` for the card's own frame, `-canvas` for
 * the Instagram letterbox behind it.
 *
 * Run after `build-share-card-assets.ts`:
 *   deno run -A scripts/build-share-card-embeds.ts
 */
const ROOT = new URL("../", import.meta.url)
const CARD_DIR = new URL("supabase/functions/_shared/setlist-share-card/", ROOT)
const ASSET_DIR = new URL("supabase/functions/_shared/share-card-assets/", ROOT)
const OUT_DIR = new URL("generated/", CARD_DIR)

const BACKGROUND_STEMS = ["newbg", "newbg2", "newbg3", "newbg4"] as const

const FONTS = [
  { file: "Geist-400.ttf", key: "geist400" },
  { file: "Geist-500.ttf", key: "geist500" },
  { file: "Geist-600.ttf", key: "geist600" },
  { file: "Geist-700.ttf", key: "geist700" },
  { file: "GeistMono-500.ttf", key: "geistMono500" },
] as const

function toBase64(bytes: Uint8Array): string {
  let binary = ""
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return btoa(binary)
}

const BANNER = (what: string) =>
  `// GENERATED by scripts/build-share-card-embeds.ts — do not edit.\n` +
  `// ${what}\n` +
  `// Embedded rather than read from disk because Supabase Edge bundles only\n` +
  `// the module graph; sibling files are not uploaded.\n\n`

await Deno.mkdir(OUT_DIR, { recursive: true })

// ---------- fonts ----------
let fontsSrc = BANNER("Geist TTFs, base64. Satori needs TTF/WOFF, not WOFF2.")
fontsSrc += `export const FONT_BASE64 = {\n`
let fontBytes = 0
for (const f of FONTS) {
  const raw = await Deno.readFile(new URL(`fonts/${f.file}`, CARD_DIR))
  fontBytes += raw.length
  fontsSrc += `  ${f.key}:\n    "${toBase64(raw)}",\n`
}
fontsSrc += `} as const\n`
await Deno.writeFile(new URL("fonts.ts", OUT_DIR), new TextEncoder().encode(fontsSrc))

// ---------- backgrounds + brand mark ----------
let bgSrc = BANNER("Pre-treated card backgrounds and the brand mark, as data URIs.")
bgSrc += `export const CARD_BACKGROUND_DATA_URI: Record<string, string> = {\n`
let bgBytes = 0
for (const stem of BACKGROUND_STEMS) {
  const raw = await Deno.readFile(new URL(`${stem}-card.jpg`, ASSET_DIR))
  bgBytes += raw.length
  bgSrc += `  "${stem}":\n    "data:image/jpeg;base64,${toBase64(raw)}",\n`
}
bgSrc += `}\n\n`

bgSrc += `export const CANVAS_BACKGROUND_DATA_URI: Record<string, string> = {\n`
for (const stem of BACKGROUND_STEMS) {
  const raw = await Deno.readFile(new URL(`${stem}-canvas.jpg`, ASSET_DIR))
  bgBytes += raw.length
  bgSrc += `  "${stem}":\n    "data:image/jpeg;base64,${toBase64(raw)}",\n`
}
bgSrc += `}\n\n`

const mark = await Deno.readFile(new URL("assets/WL-mark.png", CARD_DIR))
bgBytes += mark.length
bgSrc += `export const BRAND_MARK_DATA_URI =\n  "data:image/png;base64,${toBase64(mark)}"\n`
await Deno.writeFile(new URL("backgrounds.ts", OUT_DIR), new TextEncoder().encode(bgSrc))

const kb = (n: number) => `${(n / 1024).toFixed(0)}KB`
console.log(`fonts.ts        ${FONTS.length} files, ${kb(fontBytes)} raw -> ${kb(fontsSrc.length)} source`)
console.log(`backgrounds.ts  ${BACKGROUND_STEMS.length} backgrounds + mark, ${kb(bgBytes)} raw -> ${kb(bgSrc.length)} source`)
console.log(`\nWrote to supabase/functions/_shared/setlist-share-card/generated/`)
